### ISSUE TITLE
Only 1 out of 2 camera responds to Homey commands

### ISSUE THREAD

**Issue by Molstie** [jordenc/com.synology.surveillance#10]
First of all, thank you for creating this app. Very helpful and useful! 

However, after the last update (v2.0.0) a weird thing happened. I have 2 camera's. However, after the update, only one camera reacts on the Homey commands. Even when I give a command for camera 1, the second reacts, so:

When giving a command to camera 1, camera 1 performs the action
When giving a command to camera 2, camera 1 performs the action

Camera 2 does not respond at all.

Some additional information:

1- I already removed the camera's from Homey and added them again. 
2- I am still on Homey 1.5.13
3- The command from Homey to Synology worked perfectly before for each camera
4- The cameras are both from Foscam
5- In Synology Surv station all works normal, each camera responds to command from the web interface of Synology
6- I removed the camera 1 in the example. So, only camera 2 is known in Homey. Even then command given to camera 2, are performed on camera 1 (which is not in the Homey devices)
7- In the logs; the command coming from Homey is shown, indeed for the wrong camera (camera 1)

**Comment by jordenc** [comment]
That is strange. I will see if I can add a second device to my NAS (currently only have one)

**Comment by Tequila329** [comment]
Same here with two cams 
- Snapshot cam 1 —> cam 2 take the snapshot 
- Snapshot cam 2 —> cam 2 take the snapshot 
When i include both cams in one flow, both cams take a Snapshot.

**Comment by justjom** [comment]
I have the same issue with disabling a cam, the wrong cam gets disabled

**Comment by jordenc** [comment]
Added a second cam and can confirm this is going wrong; only the last added camera works.

I am trying to find out what is going wrong but no luck yet. Asked for some help so stay tuned :)

**Comment by jordenc** [comment]
I strongly believe I have fixed this in 2.0.1 which has been submitted for approval to the Athom app store.
