### ISSUE TITLE
Multisensor 4-in-1 motion detection not working

### ISSUE THREAD

**Issue by B3rt** [jordenc/com.synology.surveillance#11]
The old topic is gone and i seem not te be able to respond...

-------
I got a reply by mail today:
First of all, I'd like to apologise for not getting back to you earlier.
As of today version 2.0.25 of the Aeotec app is available to you in the beta channel, this should fix the motion alarm functionality of this device with Homey.
Since the device isn't available for purchase anymore the changes have been made based on device documentation. Please provide us with feedback on the functionality of the device after updating so that we can confirm whether or not this issue is fixed.
-------

I hope the update is also for homey 1.5.3 and not only for homey v2, the problem occurs in v1.5.3

**Comment by jordenc** [comment]
This is the "Synology Surveillance"-app Github, not the Aeotec app :)
