### ISSUE TITLE
App crash after flow run

### ISSUE THREAD

**Issue by Patrikgolfer** [jordenc/com.synology.surveillance#14]
I did a simple flow a contact sensor that starts recording . When i press test on the flow the starts recording card becomes unavilable

**Comment by jordenc** [comment]
Does this still happen on 2.0.3?

**Comment by Patrikgolfer** [comment]
It seems ok i 2.03
Thanks / Patrik

Skickat från min iPhone

3 apr. 2019 kl. 11:40 skrev Jorden <notifications@github.com<mailto:notifications@github.com>>:


Does this still happen on 2.0.3?

**Comment by jordenc** [comment]
Good to hear, closing for now :)
