### ISSUE TITLE
Login function overwrites session option

### ISSUE THREAD

**Issue by tillhenks** [jordenc/com.synology.surveillance#3]
Hi,

The login function in driver initiates the session option parameter twice. The session parameter should have the value 'SurveillanceStation' to not have to grant DSM (desktop) app privileges to the account in question. It is overwritten by ''NodeSynologyAPI' + Math.round(Math.random() * 1e9),' which is not specified in the WebAPI.

Br,

/Henks

**Comment by jordenc** [comment]
Sorry for my late reply; you are completely correct. This is fixed in the next version.
