### ISSUE TITLE
App seems to collide with the E-mail Sender app

### ISSUE THREAD

**Issue by MatBje** [jordenc/com.synology.surveillance#6]
This app seems to collide with the E-mail sender app by the same author. Under settings, this app shows more or less the same settings as the E-mail sender while the expected fields for IP, user name and password etc do not show. I assume some ID happens to be the same between the two apps i.e. some part of the source code has been copied without changing the ID.

![image](https://user-images.githubusercontent.com/16295393/43050500-e3c8a57c-8e09-11e8-9765-cfcfe85d5ea6.png)

**Comment by jordenc** [comment]
It is actually a feature, not a bug :)

The Synology is one of my few apps that I still need to convert to the new software development kit (SDK) version. Therefor, it is not possible to use the "image tokens" that Homey implemented in SDK v2, and still uses my own version of them.

This means, that the app can "grab" images but cannot send them using the email-app, which is already converted to SDK v2. Therefor the exact same functionality is built into the Synology app.

In the new version I will remove this functionality but for now it is the only way to mail your Synology "snapshot" image.

**Comment by MatBje** [comment]
Oh, that explains. I see that my main mistake was to try to fill in the details on the settings page before actually "using" the app in a flow. So I missed the fact that your app will even allow multiple devices as the IP, port and password are entered once the Synology device is added as a device. I like it! Many thanks for explaining and for the app itself!! Cheers! /Mats
